agents:
  MinichainHelp:
    class: minichain.agents.memory_agent.MinichainHelp
    init:
      load_memory_from: .minichain/memory
    display: true
  Programmer:
    class: minichain.agents.programmer.Programmer
    init:
      load_memory_from: .minichain/memory
    display: true
  ChatGPT:
    class: minichain.agents.chatgpt.ChatGPT
    display: true
  Artist:
    class: minichain.agents.replicate_multimodal.Artist
    display: true
  WebGPT:
    class: minichain.agents.webgpt.WebGPT
    display: false
  AGI:
    class: minichain.agents.agi.AGI
    display: true
    init:
      load_memory_from: .minichain/memory
  Researcher:
    class: minichain.agents.researcher.Researcher
    init:
      load_memory_from: .minichain/memory
    display: true
  Hippocampus:
    class: minichain.agents.hippocampus.Hippocampus
    display: false
    init:
      load_memory_from: .minichain/memory
  custom_agent:
    class: minichain.agent.Agent
    display: false
    init:
      system_prompt: "answer like a pirate"